/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#bcc7de",
        "surface-dim": "#dcd9db",
        "surface-bright": "#fbf8fa",
        "secondary": "#0058be",
        "background": "#fbf8fa",
        "on-secondary-container": "#fefcff",
        "on-primary-container": "#8590a6",
        "on-surface": "#1b1b1d",
        "primary-container": "#1e293b",
        "surface-container-low": "#f5f3f4",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f3f0f2",
        "on-tertiary-container": "#8d9092",
        "on-background": "#1b1b1d",
        "on-secondary-fixed": "#001a42",
        "on-primary-fixed": "#111c2d",
        "on-secondary": "#ffffff",
        "outline-variant": "#c5c6cd",
        "on-primary-fixed-variant": "#3c475a",
        "secondary-container": "#2170e4",
        "secondary-fixed": "#d8e2ff",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#adc6ff",
        "on-error": "#ffffff",
        "tertiary": "#111516",
        "surface-container": "#f0edef",
        "surface-tint": "#545f73",
        "tertiary-fixed": "#e0e3e5",
        "inverse-surface": "#303032",
        "on-tertiary-fixed-variant": "#444749",
        "surface": "#fbf8fa",
        "tertiary-fixed-dim": "#c4c7c9",
        "surface-container-highest": "#e4e2e3",
        "on-surface-variant": "#45474c",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#bcc7de",
        "on-tertiary-fixed": "#191c1e",
        "tertiary-container": "#26292b",
        "surface-container-high": "#eae7e9",
        "error-container": "#ffdad6",
        "surface-variant": "#e4e2e3",
        "primary": "#091426",
        "on-secondary-fixed-variant": "#004395",
        "outline": "#75777d",
        "primary-fixed": "#d8e3fb"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "xl": "32px",
        "sm": "8px",
        "md": "16px",
        "container-max": "1280px",
        "margin-desktop": "32px",
        "lg": "24px",
        "base": "4px",
        "gutter": "16px",
        "xs": "4px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "neogen": ["Neogen-Black", "sans-serif"],
        "body-md": ["Inter"],
        "data-mono": ["JetBrains Mono"],
        "label-caps": ["Inter"],
        "display-lg": ["Inter"],
        "headline-md-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "title-sm": ["Inter"],
        "body-sm": ["Inter"]
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "450" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md-mobile": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}

